import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.95.3';
const db=createClient('https://flbbjvmxqmbaynrcnefv.supabase.co','sb_publishable_AvRkk9Tx-vR1M7k7P1mx3w_txvZ6teS',{auth:{storage:sessionStorage,persistSession:true}});
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=v=>new Intl.NumberFormat('vi-VN').format(v)+' ₫';let rows=[],events=[],payments=[];
const statuses={new:'Mới',requested:'Mới',contacted:'Đã liên hệ',confirmed:'Đã xác nhận',completed:'Đã hoàn thành',cancelled:'Đã hủy',no_show:'Không đến'};
function note(t){$('notice').textContent=t}function date(v){return new Date(v).toLocaleDateString('sv-SE',{timeZone:'Asia/Ho_Chi_Minh'})}function source(r){return r.source?.utm_source||r.source?.referrer||'Trực tiếp / chưa rõ'}
async function all(table){let out=[];for(let n=0;n<20;n++){const {data,error}=await db.from(table).select('*').order('created_at',{ascending:false}).range(n*500,n*500+499);if(error)throw error;out.push(...data);if(data.length<500)return out;}throw Error('Vượt 10.000 bản ghi. Cần mở rộng phân trang trước khi tổng hợp.');}
function render(){const within=r=>date(r.created_at)>=$('from').value&&date(r.created_at)<=$('to').value;const b=rows.filter(within),e=events.filter(within);const paid=payments.filter(r=>date(r.paid_at)>=$('from').value&&date(r.paid_at)<=$('to').value).reduce((a,r)=>a+Number(r.amount),0);const sessions=new Set(e.filter(r=>r.name==='page_view'&&r.session_id).map(r=>r.session_id)).size;
$('metrics').innerHTML=[['Phiên web ghi nhận',sessions],['Lượt bấm liên hệ',e.filter(r=>r.name==='contact_click').length],['Yêu cầu mới',b.length],['Tiền thực thu',money(paid)]].map(([label,value])=>`<div class="metric">${esc(label)}<strong>${esc(value)}</strong></div>`).join('');
const sources=new Map();for(const r of b)sources.set(source(r),(sources.get(source(r))||0)+1);$('sources').innerHTML=sources.size?Array.from(sources).sort((a,b)=>b[1]-a[1]).map(([s,n])=>`<div class="source"><span>${esc(s)}</span><b>${n} yêu cầu</b></div>`).join(''):'Chưa có yêu cầu trong khoảng này.';
const q=$('search').value.trim().toLowerCase();const filtered=b.filter(r=>[r.name,r.phone,r.request_code].some(v=>(v||'').toLowerCase().includes(q)));$('bookings').innerHTML=filtered.length?filtered.map(r=>`<article class="record"><div><b>${esc(r.name)}</b><p>${esc(r.phone)} · ${esc(r.channel)}</p><p>${esc(r.service)}</p><p>Giá dự kiến: ${esc(r.price||'Cần báo giá')}</p><p>Ngày mong muốn: ${esc(r.appointment_date||'Chưa chọn')} ${esc(r.appointment_time)}</p><p>${esc(r.note)}</p><p>${esc(r.request_code)}<br>Nguồn: ${esc(source(r))}</p></div><div><label>Trạng thái<select data-status="${r.id}">${Object.entries(statuses).map(([v,l])=>`<option value="${v}" ${r.status===v?'selected':''}>${l}</option>`).join('')}</select></label><p>Đã thu: ${money(payments.filter(p=>p.booking_id===r.id).reduce((a,p)=>a+Number(p.amount),0))}</p><form data-payment="${r.id}"><label>Thêm khoản thu (VND)<input type="number" min="1" max="1000000000" step="1" required placeholder="VD: 500000"></label><button>Ghi nhận khoản thu</button></form></div></article>`).join(''):'Chưa có yêu cầu phù hợp.';}
async function load(){note('Đang tải…');try{const {data:{user},error}=await db.auth.getUser();if(error||!user)throw Error('Vui lòng đăng nhập.');const {data:staff,error:sError}=await db.from('miki_crm_staff').select('id').eq('active',true).limit(1);if(sError||!staff?.length)throw Error('Tài khoản chưa được Miki cấp quyền quản trị.');[rows,events,payments]=await Promise.all(['miki_bookings','miki_events','miki_payments'].map(all));$('login').hidden=true;$('workspace').hidden=false;$('logout').hidden=false;$('updated').textContent='Cập nhật: '+new Date().toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})+' · Giờ Việt Nam';note('');render()}catch(e){note(e.message||'Không tải được dữ liệu.');}}
$('loginForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;const {error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('password').value='';if(error)note('Không đăng nhập được. Kiểm tra tài khoản và mật khẩu.');else await load();btn.disabled=false};
$('logout').onclick=async()=>{await db.auth.signOut();rows=[];events=[];payments=[];$('workspace').hidden=true;$('bookings').replaceChildren();$('login').hidden=false;$('logout').hidden=true;note('Đã đăng xuất.')};$('refresh').onclick=load;
$('bookings').onchange=async e=>{const id=e.target.dataset.status;if(!id)return;e.target.disabled=true;const {error}=await db.from('miki_bookings').update({status:e.target.value}).eq('id',id).select('id').single();if(error){note('Chưa lưu được trạng thái.');render()}else await load()};
$('bookings').onsubmit=async e=>{e.preventDefault();const id=e.target.dataset.payment;if(!id)return;const amount=Number(e.target.querySelector('input').value);if(!Number.isSafeInteger(amount)||amount<=0)return;const btn=e.submitter;btn.disabled=true;const {error}=await db.from('miki_payments').insert({booking_id:id,amount}).select('id').single();if(error){note('Chưa ghi nhận được khoản thu.');btn.disabled=false}else await load()};
const today=date(new Date());$('to').value=today;$('from').value=today.slice(0,8)+'01';for(const id of ['from','to','search'])$(id).oninput=render;
function links(){const campaign=$('campaign').value.trim().replace(/[^a-zA-Z0-9_-]/g,'').slice(0,60)||'miki_spa';$('links').innerHTML=['facebook','whatsapp','telegram','google_maps','qr'].map(s=>{const u=new URL('https://miki-spa.com/connect.html');u.searchParams.set('utm_source',s);u.searchParams.set('utm_medium',s==='qr'?'offline':'social');u.searchParams.set('utm_campaign',campaign);return `<div class="linkrow"><b>${esc(s)}</b><a href="${esc(u.href)}" target="_blank" rel="noopener">${esc(u.href)}</a></div>`}).join('')}$('campaign').oninput=links;links();const {data:{session}}=await db.auth.getSession();if(session)load();

$('signup').onclick=async()=>{if(!$('email').checkValidity()||$('email').value.trim().toLowerCase()!=='quyhuan@gmail.com'){note('Dùng email quản trị đã được cấp quyền: quyhuan@gmail.com');return}if($('password').value.length<12){note('Chọn mật khẩu ít nhất 12 ký tự.');return}$('signup').disabled=true;const {data,error}=await db.auth.signUp({email:$('email').value.trim(),password:$('password').value,options:{emailRedirectTo:'https://miki-spa.com/crm.html'}});$('password').value='';$('signup').disabled=false;if(error)note('Không tạo được tài khoản: '+error.message);else if(data.session)await load();else note('Kiểm tra email để xác nhận tài khoản, rồi quay lại đây đăng nhập. Nếu liên kết xác nhận không mở trang Miki, vẫn quay lại trang này sau khi xác nhận.');};
